import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Codama output is regenerated by `npm run generate`; linting it only
    // flags patterns the generator owns.
    "src/generated/**",
    // Playwright artifacts (gitignored, regenerated each run).
    "playwright-report/**",
    "test-results/**",
  ]),
]);

export default eslintConfig;
