"""English subtitles for the pitch.

Reads transcript-parakeet.json (word timings of assets/footage/edit.mp4), fixes
the ASR errors, groups words into short cues and writes:
  - compositions/s10-subs.html  (caption layer, one cue at a time)
  - lazo-pitch-subs-en.srt (sidecar for upload)
  - /tmp/lazo-pitch-subs/       render-only copy of the project whose index.html
                                has the caption layer on top (a second root
                                index in this folder would break `check`)

Render: npx hyperframes render /tmp/lazo-pitch-subs -o renders/<name>.mp4
"""
import json
import pathlib
import shutil

ROOT = pathlib.Path(__file__).resolve().parent.parent
SUBS_PROJECT = pathlib.Path("/tmp/lazo-pitch-subs")

# (start time of the word to fix, replacement text; "" drops the word)
FIXES = {
    8.56: "In Argentina,",
    14.88: "paystub",
    15.2: "",
    32.48: "",
    34.32: "wallets",
    42.16: "purchases",
    43.28: "interest-free",
    43.76: "",
    67.91: "comes from",
    69.03: "pool,",
    72.55: "That",
    72.87: "pool",
    73.27: "lives on",
    73.75: "Solana.",
    77.43: "collects",
    95.19: "fintech",
    103.31: "Earning",
}

# Captions always sit centred at the bottom. In the subtitled render only, the
# lower cards are lifted so they end above the caption band (~y 955).
LIFTS = {
    "s02-argentina": {"#stat, #stat-chip": 60},
    "s03-lazo": {"#ov-names .lt": 20, "#ov-layer .node, #ov-layer .arrow, #ly-chip": 50},
    "s04-planes": {"#pl-card, #gu-card": 85},
    "s05-comprador": {"#st-chip, #st-card": 20},
    "s06-comercio": {"#se-card": 70},
    "s08-pedido": {"#as-card": 120},
}

MAX_CHARS = 40
GAP = 0.6
TAIL = 0.35


def load_words():
    words = json.loads((ROOT / "transcript-parakeet.json").read_text())
    out = []
    for w in words:
        text = FIXES.get(round(w["start"], 2), w["text"])
        if text:
            out.append({"text": text, "start": w["start"], "end": w["end"]})
    return out


def text_of(ws):
    return " ".join(w["text"] for w in ws)


def balanced(ws):
    """Split a phrase into the fewest lines under MAX_CHARS with even lengths."""
    n = 1
    while len(text_of(ws)) / n > MAX_CHARS:
        n += 1
    if n == 1 or len(ws) < n:
        return [ws]
    target = len(text_of(ws)) / n
    parts, cur = [], []
    for w in ws:
        if cur and len(parts) < n - 1 and len(text_of(cur + [w])) > target + 4:
            parts.append(cur)
            cur = []
        cur.append(w)
    parts.append(cur)
    return parts


def group(words):
    # 1. phrases: break at punctuation and at pauses
    phrases, cur = [], []
    for i, w in enumerate(words):
        if cur and w["start"] - cur[-1]["end"] > GAP:
            phrases.append(cur)
            cur = []
        cur.append(w)
        if w["text"][-1] in ".?!,":
            phrases.append(cur)
            cur = []
    if cur:
        phrases.append(cur)
    # 2. glue short phrases to the next one when it fits
    merged = []
    for ph in phrases:
        if (
            merged
            and len(text_of(merged[-1])) < 18
            and merged[-1][-1]["text"][-1] not in ".?!"
            and len(text_of(merged[-1] + ph)) <= MAX_CHARS
            and ph[0]["start"] - merged[-1][-1]["end"] <= GAP
        ):
            merged[-1] = merged[-1] + ph
        else:
            merged.append(ph)
    # 3. long phrases -> balanced lines
    cues = [part for ph in merged for part in balanced(ph)]
    out = []
    for i, c in enumerate(cues):
        start = c[0]["start"]
        end = c[-1]["end"] + TAIL
        if i + 1 < len(cues):
            end = min(end, cues[i + 1][0]["start"])
        out.append({"text": text_of(c), "start": start, "end": end})
    return out


def srt_time(t):
    ms = round(t * 1000)
    h, ms = divmod(ms, 3600000)
    m, ms = divmod(ms, 60000)
    s, ms = divmod(ms, 1000)
    return f"{h:02}:{m:02}:{s:02},{ms:03}"


def main():
    cues = group(load_words())
    end = cues[-1]["end"]

    srt = "\n".join(
        f"{i}\n{srt_time(c['start'])} --> {srt_time(c['end'])}\n{c['text']}\n"
        for i, c in enumerate(cues, 1)
    )
    (ROOT / "lazo-pitch-subs-en.srt").write_text(srt)

    divs = "\n".join(
        f'        <div id="cue-{i}" class="cue"><span>{c["text"]}</span></div>'
        for i, c in enumerate(cues)
    )
    tweens = "\n".join(
        f'      tl.set("#cue-{i}", {{ opacity: 1 }}, {c["start"]:.2f});\n'
        f'      tl.set("#cue-{i}", {{ opacity: 0 }}, {c["end"]:.2f});'
        for i, c in enumerate(cues)
    )
    html = f"""<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
  </head>
  <body>
    <!-- Generated by scripts/build-subs.py; edit the script, not this file. -->
    <template>
      <style>
        @font-face {{
          font-family: "Bricolage Grotesque";
          src: url("assets/fonts/bricolage-latin.woff2") format("woff2");
          font-weight: 200 800;
          font-stretch: 75% 100%;
        }}
        #root {{
          position: absolute;
          inset: 0;
          overflow: hidden;
          pointer-events: none;
        }}
        .cue {{
          position: absolute;
          bottom: 40px;
          left: 0;
          right: 0;
          display: flex;
          justify-content: center;
          opacity: 0;
        }}
        .cue span {{
          font-family: "Bricolage Grotesque", sans-serif;
          font-size: 40px;
          font-weight: 600;
          line-height: 1.2;
          color: #f4f1ff;
          background: rgb(7 6 11 / 0.8);
          border-radius: 14px;
          padding: 10px 24px 12px;
          white-space: nowrap;
        }}
      </style>
      <div id="root" data-composition-id="s10-subs" data-width="1920" data-height="1080">
{divs}
      </div>
      <script>
      const tl = gsap.timeline({{ paused: true }});
{tweens}
      tl.set({{}}, {{}}, {end:.2f});
      window.__timelines["s10-subs"] = tl;
      </script>
    </template>
  </body>
</html>
"""
    (ROOT / "compositions/s10-subs.html").write_text(html)

    index = (ROOT / "index.html").read_text()
    anchor = '<div data-hf-id="hf-172i" id="host-s09-placa"'
    assert anchor in index, "s09 host not found in index.html"
    host = (
        f'<div id="host-s10-subs" data-composition-id="s10-subs" '
        f'data-composition-src="compositions/s10-subs.html" data-start="0" '
        f'data-duration="{end:.2f}" data-track-index="4" data-width="1920" data-height="1080"></div>\n      '
    )
    shutil.rmtree(SUBS_PROJECT, ignore_errors=True)
    SUBS_PROJECT.mkdir(parents=True)
    shutil.copytree(ROOT / "compositions", SUBS_PROJECT / "compositions")
    for comp, rules in LIFTS.items():
        path = SUBS_PROJECT / "compositions" / f"{comp}.html"
        # margins, not `translate`: GSAP folds `translate` into its own transform
        # cache and drops it on elements it moves with y. Top-anchored boxes
        # move with margin-top, bottom-anchored ones with margin-bottom.
        css = "".join(
            f"\n        {sel} {{ margin-top: -{px}px; margin-bottom: {px}px; }}" for sel, px in rules.items()
        )
        text = path.read_text()
        assert "</style>" in text, comp
        path.write_text(text.replace("</style>", css + "\n      </style>", 1))
    (SUBS_PROJECT / "assets").symlink_to(ROOT / "assets")
    for name in ("hyperframes.json", "meta.json", "package.json"):
        shutil.copy(ROOT / name, SUBS_PROJECT / name)
    (SUBS_PROJECT / "index.html").write_text(index.replace(anchor, host + anchor))
    print(f"{len(cues)} cues, last ends {end:.2f}s")
    for c in cues:
        print(f"{c['start']:6.2f}-{c['end']:6.2f} {c['text']}")


if __name__ == "__main__":
    main()
